name: java-project-78 CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download the repository code
        uses: actions/checkout@v3
        
      - name: set up JDK
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Setup gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          gradle-version: 7.4
          arguments: build
          build-root-directory: app
      - name: send report to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        
